-- ============================================================
-- Migration 020: Catálogo de servicios de salud
-- ============================================================

ALTER TABLE service_offers ALTER COLUMN scheduled_at DROP NOT NULL;

ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS consecutive INTEGER GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS specialty            VARCHAR(100);
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS service_group        VARCHAR(60);
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS service_subgroup     VARCHAR(60);
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS service_category     VARCHAR(60);
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS service_subcategory  VARCHAR(60);
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS cups                 VARCHAR(10);
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS modalities           TEXT[];
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS image_url            VARCHAR(500);
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS instructions         TEXT;
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS restrictions         TEXT;
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS risks                TEXT;
ALTER TABLE service_offers ADD COLUMN IF NOT EXISTS contraindications    TEXT;
