-- ============================================================
-- Migration 031: Catálogo oficial de la Tabla de Referencia de
-- Servicios REPS (Resolución 3100 de 2019, Anexo Técnico)
-- ============================================================
-- Reemplaza el arreglo estático TABLA_SERVICIOS_REPS que se agregó
-- en el frontend (migración 030) por una tabla real, mismo patrón
-- que cups_catalog (migración 023): código + nombre oficial, con
-- is_active para poder desactivar códigos sin borrarlos.
--
-- Fuente: TablaReferencia_Servicios__1.xlsx — se siembran las 157
-- filas de la hoja; `is_active` refleja la columna "Habilitado" del
-- archivo (154 SI, 3 NO: Transporte asistencial básico/medicalizado
-- y Atención prehospitalaria).
-- ============================================================

CREATE TABLE IF NOT EXISTS reps_service_catalog (
  service_code  VARCHAR(10)  PRIMARY KEY,
  service_name  VARCHAR(255) NOT NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

INSERT INTO reps_service_catalog (service_code, service_name, is_active) VALUES
  ('105', 'Cuidado intermedio neonatal', TRUE),
  ('106', 'Cuidado intermedio pediatrico', TRUE),
  ('107', 'Cuidado intermedio adultos', TRUE),
  ('108', 'Cuidado intensivo neonatal', TRUE),
  ('109', 'Cuidado intensivo pediatrico', TRUE),
  ('110', 'Cuidado intensivo adultos', TRUE),
  ('1101', 'Atencion del parto', TRUE),
  ('1102', 'Urgencias', TRUE),
  ('1103', 'Transporte asistencial basico', FALSE),
  ('1104', 'Transporte asistencial medicalizado', FALSE),
  ('1105', 'Atencion prehospitalaria', FALSE),
  ('120', 'Cuidado basico neonatal', TRUE),
  ('129', 'Hospitalizacion adultos', TRUE),
  ('130', 'Hospitalizacion pediatrica', TRUE),
  ('131', 'Hospitalizacion en salud mental', TRUE),
  ('132', 'Hospitalizacion parcial', TRUE),
  ('133', 'Hospitalizacion paciente cronico con ventilador', TRUE),
  ('134', 'Hospitalizacion paciente cronico sin ventilador', TRUE),
  ('135', 'Hospitalizacion en consumo de sustancias psicoactivas', TRUE),
  ('138', 'Cuidado basico del consumo de sustancias psicoactivas', TRUE),
  ('201', 'Cirugia de cabeza y cuello', TRUE),
  ('202', 'Cirugia cardiovascular', TRUE),
  ('203', 'Cirugia general', TRUE),
  ('204', 'Cirugia ginecologica', TRUE),
  ('205', 'Cirugia maxilofacial', TRUE),
  ('207', 'Cirugia ortopedica', TRUE),
  ('208', 'Cirugia oftalmologica', TRUE),
  ('209', 'Cirugia otorrinolaringologia', TRUE),
  ('210', 'Cirugia oncologica', TRUE),
  ('211', 'Cirugia oral', TRUE),
  ('212', 'Cirugia pediatrica', TRUE),
  ('213', 'Cirugia plastica y estetica', TRUE),
  ('214', 'Cirugia vascular y angiologica', TRUE),
  ('215', 'Cirugia urologica', TRUE),
  ('217', 'Otras cirugias', TRUE),
  ('218', 'Cirugia endovascular neurologica', TRUE),
  ('227', 'Cirugia oncologica pediatrica', TRUE),
  ('231', 'Cirugia de la mano', TRUE),
  ('232', 'Cirugia de mama y tumores tejidos blandos', TRUE),
  ('233', 'Cirugia dermatologica', TRUE),
  ('234', 'Cirugia de torax', TRUE),
  ('235', 'Cirugia gastrointestinal', TRUE),
  ('237', 'Cirugia plastica oncologica', TRUE),
  ('245', 'Neurocirugia', TRUE),
  ('301', 'Anestesia', TRUE),
  ('302', 'Cardiologia', TRUE),
  ('303', 'Cirugia cardiovascular', TRUE),
  ('304', 'Cirugia general', TRUE),
  ('306', 'Cirugia pediatrica', TRUE),
  ('308', 'Dermatologia', TRUE),
  ('309', 'Dolor y cuidados paliativos', TRUE),
  ('310', 'Endocrinologia', TRUE),
  ('311', 'Endodoncia', TRUE),
  ('312', 'Enfermeria', TRUE),
  ('313', 'Estomatologia', TRUE),
  ('316', 'Gastroenterologia', TRUE),
  ('317', 'Genetica', TRUE),
  ('318', 'Geriatria', TRUE),
  ('320', 'Ginecobstetricia', TRUE),
  ('321', 'Hematologia', TRUE),
  ('323', 'Infectologia', TRUE),
  ('324', 'Inmunologia', TRUE),
  ('325', 'Medicina familiar', TRUE),
  ('326', 'Medicina fisica y del deporte', TRUE),
  ('327', 'Medicina fisica y rehabilitacion', TRUE),
  ('328', 'Medicina general', TRUE),
  ('329', 'Medicina interna', TRUE),
  ('330', 'Nefrologia', TRUE),
  ('331', 'Neumologia', TRUE),
  ('332', 'Neurologia', TRUE),
  ('333', 'Nutricion y dietetica', TRUE),
  ('334', 'Odontologia general', TRUE),
  ('335', 'Oftalmologia', TRUE),
  ('336', 'Oncologia clinica', TRUE),
  ('337', 'Optometria', TRUE),
  ('338', 'Ortodoncia', TRUE),
  ('339', 'Ortopedia y/o traumatologia', TRUE),
  ('340', 'Otorrinolaringologia', TRUE),
  ('342', 'Pediatria', TRUE),
  ('343', 'Periodoncia', TRUE),
  ('344', 'Psicologia', TRUE),
  ('345', 'Psiquiatria', TRUE),
  ('346', 'Rehabilitacion oncologica', TRUE),
  ('347', 'Rehabilitacion oral', TRUE),
  ('348', 'Reumatologia', TRUE),
  ('354', 'Toxicologia', TRUE),
  ('355', 'Urologia', TRUE),
  ('356', 'Otras consultas de especialidad', TRUE),
  ('361', 'Cardiologia pediatrica', TRUE),
  ('362', 'Cirugia de cabeza y cuello', TRUE),
  ('363', 'Cirugia de mano', TRUE),
  ('364', 'Cirugia de mama y tumores tejidos blandos', TRUE),
  ('365', 'Cirugia dermatologica', TRUE),
  ('366', 'Cirugia de torax', TRUE),
  ('367', 'Cirugia gastrointestinal', TRUE),
  ('368', 'Cirugia ginecologica laparoscopica', TRUE),
  ('369', 'Cirugia plastica y estetica', TRUE),
  ('370', 'Cirugia plastica oncologica', TRUE),
  ('371', 'Otras consultas generales', TRUE),
  ('372', 'Cirugia vascular', TRUE),
  ('373', 'Cirugia oncologica', TRUE),
  ('374', 'Cirugia oncologica pediatrica', TRUE),
  ('375', 'Dermatologia oncologica', TRUE),
  ('377', 'Coloproctologia', TRUE),
  ('379', 'Ginecologia oncologica', TRUE),
  ('383', 'Medicina nuclear', TRUE),
  ('384', 'Nefrologia pediatrica', TRUE),
  ('385', 'Neonatologia', TRUE),
  ('386', 'Neumologia pediatrica', TRUE),
  ('387', 'Neurocirugia', TRUE),
  ('388', 'Neuropediatria', TRUE),
  ('390', 'Oftalmologia oncologica', TRUE),
  ('391', 'Oncologia y hematologia pediatrica', TRUE),
  ('393', 'Ortopedia oncologica', TRUE),
  ('395', 'Urologia oncologica', TRUE),
  ('396', 'Odontopediatria', TRUE),
  ('397', 'Medicina estetica', TRUE),
  ('406', 'Hematologia oncologica', TRUE),
  ('407', 'Medicina del trabajo y medicina laboral', TRUE),
  ('408', 'Radioterapia', TRUE),
  ('409', 'Ortopedia pediatrica', TRUE),
  ('410', 'Cirugia oral', TRUE),
  ('411', 'Cirugia maxilofacial', TRUE),
  ('412', 'Medicina alternativa y complementaria - homeopatica', TRUE),
  ('413', 'Medicina alternativa y complementaria - ayurvedica', TRUE),
  ('414', 'Medicina alternativa y complementaria - tradicional china', TRUE),
  ('415', 'Medicina alternativa y complementaria - naturopatica', TRUE),
  ('416', 'Medicina alternativa y complementaria - neuralterapeutica', TRUE),
  ('417', 'Terapias alternativas y complementarias - bioenergetica', TRUE),
  ('418', 'Terapias alternativas y complementarias - terapia con filtros', TRUE),
  ('419', 'Terapias alternativas y complementarias - terapias manuales', TRUE),
  ('420', 'Vacunacion', TRUE),
  ('421', 'Patologia', TRUE),
  ('422', 'Medicina alternativa y complementaria - osteopatica', TRUE),
  ('423', 'Seguridad y salud en el trabajo', TRUE),
  ('706', 'Laboratorio clinico', TRUE),
  ('709', 'Quimioterapia', TRUE),
  ('711', 'Radioterapia', TRUE),
  ('712', 'Toma de muestras de laboratorio clinico', TRUE),
  ('714', 'Servicio farmaceutico', TRUE),
  ('715', 'Medicina nuclear', TRUE),
  ('717', 'Laboratorio citologias cervico-uterinas', TRUE),
  ('728', 'Terapia ocupacional', TRUE),
  ('729', 'Terapia respiratoria', TRUE),
  ('731', 'Laboratorio de histotecnologia', TRUE),
  ('733', 'Hemodialisis', TRUE),
  ('734', 'Dialisis peritoneal', TRUE),
  ('739', 'Fisioterapia', TRUE),
  ('740', 'Fonoaudiologia y/o terapia del lenguaje', TRUE),
  ('742', 'Diagnostico vascular', TRUE),
  ('743', 'Hemodinamia e intervencionismo', TRUE),
  ('744', 'Imagenes diagnosticas - ionizantes', TRUE),
  ('745', 'Imagenes diagnosticas - no ionizantes', TRUE),
  ('746', 'Gestion pre-transfusional', TRUE),
  ('747', 'Patologia', TRUE),
  ('748', 'Radiologia odontologica', TRUE),
  ('749', 'Toma de muestras de cuello uterino y ginecologicas', TRUE)
ON CONFLICT (service_code) DO NOTHING;

-- FK: service_catalog.reps_service_code (migración 030) sólo puede apuntar a
-- un código real de este catálogo. Patrón DROP/ADD para que la migración sea
-- reejecutable (ver migración 026).
ALTER TABLE service_catalog DROP CONSTRAINT IF EXISTS service_catalog_reps_service_code_fkey;
ALTER TABLE service_catalog
  ADD CONSTRAINT service_catalog_reps_service_code_fkey
  FOREIGN KEY (reps_service_code) REFERENCES reps_service_catalog(service_code);
